name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Iniciar Workflow
        run: echo "Iniciando el workflow..."

  validate-html:
    needs: start
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Validar HTML
        uses: javanile/htmlchecker-action@v1

  deploy:
    needs: validate-html
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v3

      - name: Subir archivos a GitHub Pages
        uses: actions/upload-pages-artifact@v2

      - name: Desplegar en GitHub Pages
        uses: actions/deploy-pages@v2
