 name: Deploy Website

on:
  push:
    branches:
      - main
 

jobs:
  validate-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v3

      - name: Validar HTML
        uses: Cyb3r-Jak3/html5-validar-action@v1
        with:
          file: index.html
Deploy:
  needs: validate-html
  runs-on: ubuntu-latest
  steps:
    -name: Checkout del codigo
    uses: actions/checkout@v3

    -name: Configurar Github Pages
    uses: actions/configure-pages@v3

    -name: Publicar en Github Pages
    uses: actions/upload-pages-artifact@v2

